/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs_3560_project.app;

import static cs_3560_project.app.App.w;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author Nerve Center
 */
public class MainJFrame extends javax.swing.JFrame {

    public final String MENU = "menu";
    public final String LOAN = "loan";
    public final String INVENTORY = "inventory";
    public final String MANAGEMENT = "management";
    private final CardLayout cLayout;
    private final JPanel mainPane;
    private MenuScreen menuScreen;
    private LoanScreen loanScreen;
    private ItemScreen inventoryScreen;
    private ManagementScreen managementScreen;
    
    
    /**
     * Creates new form MainJFrame
     * @param menuScreen
     * @param loanScreen
     * @param inventoryScreen
     * @param managementScreen
     * @throws java.lang.InterruptedException
     */
    public MainJFrame(JPanel menuScreen, 
            JPanel loanScreen, 
            JPanel inventoryScreen, 
            JPanel managementScreen) throws InterruptedException {
        initComponents();
        
        setTitle("It's Morbin Time!");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        mainPane = new JPanel();
        mainPane.setPreferredSize(new Dimension(600,400));
        cLayout = new CardLayout();
        mainPane.setLayout(cLayout);
        
        /**menuScreen = this.menuScreen;
        loanScreen = this.loanScreen;
        inventoryScreen = this.inventoryScreen;
        managementScreen = this.managementScreen;**/

        mainPane.add(MENU, menuScreen);
        mainPane.add(LOAN, loanScreen);
        mainPane.add(INVENTORY, inventoryScreen);
        mainPane.add(MANAGEMENT, managementScreen);
        
        cLayout.show(mainPane, MENU);
        
        setLayout(new BorderLayout());
        add(mainPane,BorderLayout.CENTER);
        pack();
        setVisible(true);
        
        setUpKeyBindings();
    }
    
    private void setUpKeyBindings()
    {
        InputMap myInputMap;
        ActionMap myActionMap;
        
        Action exitProgram = new AbstractAction(){
         @Override
         public void actionPerformed(ActionEvent evt) {
                w.dispatchEvent(new WindowEvent(w, WindowEvent.WINDOW_CLOSING));
             }
        };
        
       // GameScreen = this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        myInputMap = mainPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        myActionMap = mainPane.getActionMap();
        
        
        myInputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "exit");
        myActionMap.put("exit", exitProgram);
    }
    
    // method: switchPanes(String swap)
    // purpose: this method allows to easily switch screens to the corresponding
    // name given for the screen
    void switchPanes(String swap) {
        cLayout.show(mainPane, swap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
