/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cs_3560_project.app;

import static cs_3560_project.app.App.w;

/**
 *
 * @author Nerve Center
 */
public class ManagementScreen extends javax.swing.JPanel {

    private Integer status = 0; //Modulo3 0-Student, Modulo3 1-Book, Modulo3 2-Documentary
    
    /**
     * Creates new form ItemScreen
     */
    public ManagementScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        BackButton2 = new javax.swing.JButton();
        SwapButton = new javax.swing.JButton();
        InputField = new javax.swing.JTextField();
        CreateButton = new javax.swing.JRadioButton();
        ReadButton = new javax.swing.JRadioButton();
        UpdateButton = new javax.swing.JRadioButton();
        DeleteButton = new javax.swing.JRadioButton();
        RunButton = new javax.swing.JButton();

        buttonGroup1.add(CreateButton);
        buttonGroup1.add(ReadButton);
        buttonGroup1.add(UpdateButton);
        buttonGroup1.add(DeleteButton);

        jLabel1.setText("Management");

        BackButton2.setText("Back");
        BackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton2ActionPerformed(evt);
            }
        });

        SwapButton.setText("Book");
        SwapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwapButtonActionPerformed(evt);
            }
        });

        InputField.setText("Input");
        InputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFieldActionPerformed(evt);
            }
        });

        CreateButton.setText("Create");
        CreateButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        ReadButton.setText("Read");
        ReadButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        UpdateButton.setText("Update");
        UpdateButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        DeleteButton.setText("Delete");
        DeleteButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        RunButton.setText("Run");
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RunButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteButton)
                    .addComponent(CreateButton)
                    .addComponent(ReadButton)
                    .addComponent(UpdateButton))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(SwapButton)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackButton2)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SwapButton))
                .addGap(34, 34, 34)
                .addComponent(CreateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReadButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RunButton)
                    .addComponent(UpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(BackButton2)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton2ActionPerformed
        w.switchPanes("menu");
        
    }//GEN-LAST:event_BackButton2ActionPerformed

    private void SwapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwapButtonActionPerformed
        if(status % 3 == 0) {
            SwapButton.setText("Documentary");
        }
        else if(status % 3 == 1) {
            SwapButton.setText("Student");
        }
        else {
            SwapButton.setText("Book");
        }
        status++;
    }//GEN-LAST:event_SwapButtonActionPerformed

    private void InputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFieldActionPerformed

    private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed
        if(status % 3 == 0) {
            if(CreateButton.isSelected()) {
                //Create code for student
            }
            if(ReadButton.isSelected()) {
                //Read code for student
            }
            if(UpdateButton.isSelected()) {
                //Update code for student
            }
            if(DeleteButton.isSelected()) {
                //Delete code for student
            }
        }
        else if(status % 3 == 1) {
            if(CreateButton.isSelected()) {
                //Create code for book
            }
            if(ReadButton.isSelected()) {
                //Read code for book
            }
            if(UpdateButton.isSelected()) {
                //Update code for book
            }
            if(DeleteButton.isSelected()) {
                //Delete code for book
            }
        }
        else {
            if (CreateButton.isSelected()) {
                //Create code for documentary
            }
            if (ReadButton.isSelected()) {
                //Read code for documentary
            }
            if (UpdateButton.isSelected()) {
                //Update code for documentary
            }
            if (DeleteButton.isSelected()) {
                //Delete code for documentary
            }
        }
    }//GEN-LAST:event_RunButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton2;
    private javax.swing.JRadioButton CreateButton;
    private javax.swing.JRadioButton DeleteButton;
    private javax.swing.JTextField InputField;
    private javax.swing.JRadioButton ReadButton;
    private javax.swing.JButton RunButton;
    private javax.swing.JButton SwapButton;
    private javax.swing.JRadioButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
